### ISSUE TITLE
Problem with hipoly meshes

### ISSUE THREAD

**Issue by brothermechanic** [mrachinskiy/blender-addon-booltron#1]
Hello
I found a bug
In this scene  https://db.tt/gMTBPDuy you found 2 objects 
Try to "union" them with booltron
This operation works wrong for this meshes
resoult http://wstaw.org/m/2015/10/15/plasma-desktopmQ4771.png
However, a boolean modifier do "union" fine!
Please fix it

Thank you for useful plugin!

**Comment by mrachinskiy** [comment]
Thanks for the report, I'll look into that.

**Comment by mrachinskiy** [comment]
The model you provided contains intersecting faces resulting in non-manifold and loose geometry after a boolean union operation. If loose geometry detected Booltron automatically splits union result into a separate objects to repeat union operation. In your case union operation between multiple non-manifold objects resulting in complete destruction of the initial geometry.

If you do union operation with boolean modifier and check the result you'll see all errors I am talking about. And with another boolean operation using boolean modifier (for example with left wing), you will get the same result you initially got with Booltron.

I know how to stop the second union operation from happening after loose geometry split so you could get your (non-manifold) union result, but I have no way of telling that to a user, since Blender does not have a modal dialog popups, I'm afraid result of that operation will be even more confusing.

Until I come up with a better solution I leave add-on as is, with simple workflow logic: “bad result after boolean operation—means bad input geometry.”

**Comment by mrachinskiy** [comment]
Update on the state of the issue here: in this commit d7bd183 I added mesh check that will stop boolean union operation from repeating and show a warning if the result is non-manifold.
So boolean operation on the model you provided will complete much faster, it will not destroy model and will show a warning about non-manifold geometry upon completion. So you'll know something is wrong with the geometry of your model, or if something bad happened during boolean operation.
It will work the same for other boolean tools in the add-on.

See [full change log](https://www.facebook.com/notes/mikhail-rachinskiy/booltron-super-add-on-update/1107142466046672) to understand how it works (contains GIF animation).
